version: '3'

services:
  db:
    image: mysql
    command: --authentication-policy=mysql_native_password && --innodb-use-native-aio=0 
    restart: always
    container_name: db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nginx-network
    expose:
      - "3306"
  app:
    container_name: app
    entrypoint: "dockerize --wait tcp://db:3306 --timeout 20s node index.js"
    tty: true
    volumes:
      - ./node:/app
    build: 
      context: ./node
    networks:
      - nginx-network
    depends_on:
      - db
  nginx:
    entrypoint: "dockerize --wait http://app:3000/ --timeout 30s /docker-entrypoint.sh"
    command: ["nginx" ,"-g", "daemon off;"]
    tty: true
    volumes:
      - ./nginx:/etc/nginx/
    build:
      context: ./nginx
    container_name: nginx-proxy-reverse
    networks:
      - nginx-network
    ports: 
      - "8080:80"
    depends_on:
      - app
networks:
  nginx-network:
    driver: bridge
